server:
  port: 8080

spring:
  application:
    name: hr-leave-management

  datasource:
    url: jdbc:mysql://database-1.crus6wwka0x8.ap-south-2.rds.amazonaws.com:3306/mysql?useSSL=true&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 7000150409

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.security: INFO

app:
  seed-demo-data: true
